import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "./globals.scss";
import SiderBar from "@/components/SiderBar";

const roboto = Roboto({ subsets: ["cyrillic"], weight: ["400", "500", "700"] });

export const metadata: Metadata = {
  title: "Films App",
  description: "Films App, generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={roboto.className}>
        <div className="wrapper">
          <SiderBar />
          <main className="container">
            <AntdRegistry>{children}</AntdRegistry>
          </main>
        </div>
      </body>
    </html>
  );
}
